[2022-10-26 13:33:11,202] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:11,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:33:11,251] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:11,251] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:33:11,251] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:33:11,322] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): juegos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:33:11,341] {standard_task_runner.py:52} INFO - Started process 347 to run task
[2022-10-26 13:33:11,362] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'juegos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp20io2mqt', '--error-file', '/tmp/tmpaf3fuhv4']
[2022-10-26 13:33:11,365] {standard_task_runner.py:80} INFO - Job 2: Subtask juegos_raw_create
[2022-10-26 13:33:11,633] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:33:12,083] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=juegos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:33:12,322] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres-default` isn't defined
[2022-10-26 13:33:12,333] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=load_raw_data, task_id=juegos_raw_create, execution_date=20220901T000000, start_date=20221026T133311, end_date=20221026T133312
[2022-10-26 13:33:12,421] {standard_task_runner.py:97} ERROR - Failed to execute job 2 for task juegos_raw_create (The conn_id `postgres-default` isn't defined; 347)
[2022-10-26 13:33:12,482] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-26 13:33:12,844] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:29,464] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,513] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:29,513] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,513] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:29,513] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:29,641] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): juegos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:29,655] {standard_task_runner.py:52} INFO - Started process 252 to run task
[2022-10-26 14:27:29,685] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'juegos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp6e9nth6r', '--error-file', '/tmp/tmpdcykfdob']
[2022-10-26 14:27:29,694] {standard_task_runner.py:80} INFO - Job 6: Subtask juegos_raw_create
[2022-10-26 14:27:29,921] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:30,901] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=juegos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:30,956] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:30,989] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS juegos_raw (juego_id serial primary key,
                                                                                nombre_juego varchar(100),
                                                                                annio integer,
                                                                                temporada varchar(100),
                                                                                ciudad varchar(100));
                        , parameters: None
[2022-10-26 14:27:31,043] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=juegos_raw_create, execution_date=20220901T000000, start_date=20221026T142729, end_date=20221026T142731
[2022-10-26 14:27:31,106] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:31,267] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:44,013] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:44,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:44,035] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:44,035] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:44,036] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:44,080] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): juegos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:44,088] {standard_task_runner.py:52} INFO - Started process 280 to run task
[2022-10-26 14:47:44,117] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'juegos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp_xlo32g6', '--error-file', '/tmp/tmpennn53ct']
[2022-10-26 14:47:44,119] {standard_task_runner.py:80} INFO - Job 4: Subtask juegos_raw_create
[2022-10-26 14:47:44,311] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:44,570] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=juegos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:44,671] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:44,683] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS juegos_raw (juego_id serial primary key,
                                                                                nombre_juego varchar(100),
                                                                                annio integer,
                                                                                temporada varchar(100),
                                                                                ciudad varchar(100));
                        , parameters: None
[2022-10-26 14:47:44,743] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=juegos_raw_create, execution_date=20220901T000000, start_date=20221026T144744, end_date=20221026T144744
[2022-10-26 14:47:44,807] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:44,925] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 17:10:48,981] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:49,003] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:49,004] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:49,004] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 17:10:49,004] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:49,038] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): juegos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 17:10:49,076] {standard_task_runner.py:52} INFO - Started process 248 to run task
[2022-10-26 17:10:49,130] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'juegos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp5roa0yi9', '--error-file', '/tmp/tmp9ip_g4f7']
[2022-10-26 17:10:49,147] {standard_task_runner.py:80} INFO - Job 4: Subtask juegos_raw_create
[2022-10-26 17:10:49,855] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 553edc2a1daa
[2022-10-26 17:10:50,998] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=juegos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 17:10:51,152] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 17:10:51,198] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS juegos_raw (juego_id serial primary key,
                                                                                nombre_juego varchar(100),
                                                                                annio integer,
                                                                                temporada varchar(100),
                                                                                ciudad varchar(100));
                        , parameters: None
[2022-10-26 17:10:51,350] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=juegos_raw_create, execution_date=20220901T000000, start_date=20221026T171048, end_date=20221026T171051
[2022-10-26 17:10:51,435] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 17:10:51,726] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-29 18:23:13,183] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 18:23:13,220] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 18:23:13,220] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 18:23:13,221] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-29 18:23:13,221] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 18:23:13,297] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): juegos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-29 18:23:13,306] {standard_task_runner.py:52} INFO - Started process 209 to run task
[2022-10-29 18:23:13,345] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'juegos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp5_dom_6e', '--error-file', '/tmp/tmp4g28ka55']
[2022-10-29 18:23:13,347] {standard_task_runner.py:80} INFO - Job 5: Subtask juegos_raw_create
[2022-10-29 18:23:13,605] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.juegos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d3faad85a14a
[2022-10-29 18:23:13,982] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=juegos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-29 18:23:14,010] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-29 18:23:14,024] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS oly.juegos_raw (juego_id serial primary key,
                                                                                nombre_juego varchar(100),
                                                                                annio integer,
                                                                                temporada varchar(100),
                                                                                ciudad varchar(100));
                        , parameters: None
[2022-10-29 18:23:14,136] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=juegos_raw_create, execution_date=20220901T000000, start_date=20221029T182313, end_date=20221029T182314
[2022-10-29 18:23:14,204] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-29 18:23:14,545] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
