[2022-10-26 13:37:52,832] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:52,853] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:52,853] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:52,854] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:37:52,854] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:52,881] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): eventos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:37:52,887] {standard_task_runner.py:52} INFO - Started process 464 to run task
[2022-10-26 13:37:52,892] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'eventos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpjk1x5x9x', '--error-file', '/tmp/tmpx2lfksv4']
[2022-10-26 13:37:52,893] {standard_task_runner.py:80} INFO - Job 19: Subtask eventos_raw_create
[2022-10-26 13:37:53,007] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:37:53,233] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=eventos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:37:53,249] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 13:37:53,255] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS eventos_raw (evento_id serial primary key,
                                                                                evento varchar(100),
                                                                                deporte_id integer REFERENCES deportes_raw (deporte_id));
                        , parameters: None
[2022-10-26 13:37:53,287] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=eventos_raw_create, execution_date=20220901T000000, start_date=20221026T133752, end_date=20221026T133753
[2022-10-26 13:37:53,329] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 13:37:53,448] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:34,581] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:34,594] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:34,594] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:34,594] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:34,594] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:34,614] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): eventos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:34,622] {standard_task_runner.py:52} INFO - Started process 264 to run task
[2022-10-26 14:27:34,629] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'eventos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmptpjdklv0', '--error-file', '/tmp/tmp5yxq22l6']
[2022-10-26 14:27:34,631] {standard_task_runner.py:80} INFO - Job 12: Subtask eventos_raw_create
[2022-10-26 14:27:34,703] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:34,826] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=eventos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:34,839] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:34,844] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS eventos_raw (evento_id serial primary key,
                                                                                evento varchar(100),
                                                                                deporte_id integer REFERENCES deportes_raw (deporte_id));
                        , parameters: None
[2022-10-26 14:27:34,872] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=eventos_raw_create, execution_date=20220901T000000, start_date=20221026T142734, end_date=20221026T142734
[2022-10-26 14:27:34,921] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:34,986] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:47,855] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:47,879] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:47,879] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:47,880] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:47,880] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:47,906] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): eventos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:47,912] {standard_task_runner.py:52} INFO - Started process 292 to run task
[2022-10-26 14:47:47,918] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'eventos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmplz8di7vp', '--error-file', '/tmp/tmpjzgmlbgf']
[2022-10-26 14:47:47,919] {standard_task_runner.py:80} INFO - Job 11: Subtask eventos_raw_create
[2022-10-26 14:47:48,014] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:48,158] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=eventos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:48,177] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:48,183] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS eventos_raw (evento_id serial primary key,
                                                                                evento varchar(100),
                                                                                deporte_id integer REFERENCES deportes_raw (deporte_id));
                        , parameters: None
[2022-10-26 14:47:48,217] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=eventos_raw_create, execution_date=20220901T000000, start_date=20221026T144747, end_date=20221026T144748
[2022-10-26 14:47:48,250] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:48,305] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 17:10:55,718] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:55,768] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:10:55,768] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:55,768] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 17:10:55,769] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:10:55,875] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): eventos_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 17:10:55,881] {standard_task_runner.py:52} INFO - Started process 263 to run task
[2022-10-26 17:10:55,886] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'eventos_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpsrqvypka', '--error-file', '/tmp/tmp6jpxjo_b']
[2022-10-26 17:10:55,888] {standard_task_runner.py:80} INFO - Job 12: Subtask eventos_raw_create
[2022-10-26 17:10:56,054] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.eventos_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 553edc2a1daa
[2022-10-26 17:10:56,328] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=eventos_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 17:10:56,377] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 17:10:56,386] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS eventos_raw (evento_id serial primary key,
                                                                                evento varchar(100),
                                                                                deporte_id integer REFERENCES deportes_raw (deporte_id));
                        , parameters: None
[2022-10-26 17:10:56,455] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=eventos_raw_create, execution_date=20220901T000000, start_date=20221026T171055, end_date=20221026T171056
[2022-10-26 17:10:56,525] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 17:10:56,743] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
