[2022-10-26 13:37:58,546] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:58,565] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:58,565] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:58,566] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:37:58,566] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:58,589] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): resultados_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:37:58,594] {standard_task_runner.py:52} INFO - Started process 481 to run task
[2022-10-26 13:37:58,597] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'resultados_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpk9rc6vde', '--error-file', '/tmp/tmpjwzda8vx']
[2022-10-26 13:37:58,599] {standard_task_runner.py:80} INFO - Job 23: Subtask resultados_raw_create
[2022-10-26 13:37:58,673] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:37:58,782] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=resultados_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:37:58,820] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 13:37:58,827] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS resultados_raw (resultado_id serial primary key,
                                                                                    medalla varchar(100),
                                                                                    deportista_id integer REFERENCES deportistas_raw (deportista_id),
                                                                                    juego_id integer REFERENCES juegos_raw (juego_id),
                                                                                    evento_id integer REFERENCES eventos_raw (evento_id));
                        , parameters: None
[2022-10-26 13:37:58,868] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=resultados_raw_create, execution_date=20220901T000000, start_date=20221026T133758, end_date=20221026T133758
[2022-10-26 13:37:58,930] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 13:37:59,042] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:39,642] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:39,656] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:39,657] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:39,657] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:39,657] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:39,677] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): resultados_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:39,681] {standard_task_runner.py:52} INFO - Started process 271 to run task
[2022-10-26 14:27:39,685] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'resultados_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp4240_4cj', '--error-file', '/tmp/tmpjvfy8k3n']
[2022-10-26 14:27:39,686] {standard_task_runner.py:80} INFO - Job 15: Subtask resultados_raw_create
[2022-10-26 14:27:39,772] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:39,865] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=resultados_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:39,877] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:39,882] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS resultados_raw (resultado_id serial primary key,
                                                                                    medalla varchar(100),
                                                                                    deportista_id integer REFERENCES deportistas_raw (deportista_id),
                                                                                    juego_id integer REFERENCES juegos_raw (juego_id),
                                                                                    evento_id integer REFERENCES eventos_raw (evento_id));
                        , parameters: None
[2022-10-26 14:27:39,910] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=resultados_raw_create, execution_date=20220901T000000, start_date=20221026T142739, end_date=20221026T142739
[2022-10-26 14:27:39,937] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:39,981] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:53,350] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:53,364] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:53,365] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:53,365] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:53,365] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:53,385] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): resultados_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:53,389] {standard_task_runner.py:52} INFO - Started process 310 to run task
[2022-10-26 14:47:53,392] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'resultados_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp_n4pge28', '--error-file', '/tmp/tmpdborxdgt']
[2022-10-26 14:47:53,393] {standard_task_runner.py:80} INFO - Job 15: Subtask resultados_raw_create
[2022-10-26 14:47:53,462] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:53,558] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=resultados_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:53,571] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:53,576] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS resultados_raw (resultado_id serial primary key,
                                                                                    medalla varchar(100),
                                                                                    deportista_id integer REFERENCES deportistas_raw (deportista_id),
                                                                                    juego_id integer REFERENCES juegos_raw (juego_id),
                                                                                    evento_id integer REFERENCES eventos_raw (evento_id));
                        , parameters: None
[2022-10-26 14:47:53,603] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=resultados_raw_create, execution_date=20220901T000000, start_date=20221026T144753, end_date=20221026T144753
[2022-10-26 14:47:53,645] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:53,688] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 17:11:04,040] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:11:04,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 17:11:04,055] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:11:04,055] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 17:11:04,055] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 17:11:04,078] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): resultados_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-26 17:11:04,091] {standard_task_runner.py:52} INFO - Started process 270 to run task
[2022-10-26 17:11:04,094] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'resultados_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp120scqqu', '--error-file', '/tmp/tmp_y9qzm5f']
[2022-10-26 17:11:04,095] {standard_task_runner.py:80} INFO - Job 15: Subtask resultados_raw_create
[2022-10-26 17:11:04,179] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host 553edc2a1daa
[2022-10-26 17:11:04,299] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=resultados_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 17:11:04,312] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 17:11:04,320] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS resultados_raw (resultado_id serial primary key,
                                                                                    medalla varchar(100),
                                                                                    deportista_id integer REFERENCES deportistas_raw (deportista_id),
                                                                                    juego_id integer REFERENCES juegos_raw (juego_id),
                                                                                    evento_id integer REFERENCES eventos_raw (evento_id));
                        , parameters: None
[2022-10-26 17:11:04,507] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=resultados_raw_create, execution_date=20220901T000000, start_date=20221026T171104, end_date=20221026T171104
[2022-10-26 17:11:04,589] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 17:11:04,674] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-29 18:32:02,791] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 18:32:02,807] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-29 18:32:02,807] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 18:32:02,807] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-29 18:32:02,808] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-29 18:32:02,830] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): resultados_raw_create> on 2022-09-01 00:00:00+00:00
[2022-10-29 18:32:02,834] {standard_task_runner.py:52} INFO - Started process 417 to run task
[2022-10-29 18:32:02,838] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'resultados_raw_create', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpjwnbkwyb', '--error-file', '/tmp/tmpj7ryaiic']
[2022-10-29 18:32:02,839] {standard_task_runner.py:80} INFO - Job 19: Subtask resultados_raw_create
[2022-10-29 18:32:02,907] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.resultados_raw_create scheduled__2022-09-01T00:00:00+00:00 [running]> on host d3faad85a14a
[2022-10-29 18:32:03,011] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=resultados_raw_create
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-29 18:32:03,027] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-29 18:32:03,032] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS oly.resultados_raw (resultado_id serial primary key,
                                                                                    medalla varchar(100),
                                                                                    deportista_id integer REFERENCES oly.deportistas_raw (deportista_id),
                                                                                    juego_id integer REFERENCES oly.juegos_raw (juego_id),
                                                                                    evento_id integer REFERENCES oly.eventos_raw (evento_id));
                        , parameters: None
[2022-10-29 18:32:03,064] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=resultados_raw_create, execution_date=20220901T000000, start_date=20221029T183202, end_date=20221029T183203
[2022-10-29 18:32:03,090] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-29 18:32:03,150] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
