[2022-10-26 13:37:50,852] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:50,901] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 13:37:50,902] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:50,902] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 13:37:50,902] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 13:37:50,952] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_populate> on 2022-09-01 00:00:00+00:00
[2022-10-26 13:37:50,961] {standard_task_runner.py:52} INFO - Started process 459 to run task
[2022-10-26 13:37:50,971] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_populate', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmpbv2ycqny', '--error-file', '/tmp/tmplc_jr5_z']
[2022-10-26 13:37:50,982] {standard_task_runner.py:80} INFO - Job 16: Subtask generos_raw_populate
[2022-10-26 13:37:51,157] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [running]> on host b1681a16582a
[2022-10-26 13:37:51,456] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_populate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 13:37:51,489] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 13:37:51,496] {dbapi.py:208} INFO - Running statement: 
                            INSERT INTO generos_raw (genero_id, genero) VALUES(1,'M');
                            INSERT INTO generos_raw (genero_id, genero) VALUES(2,'F');
                        , parameters: None
[2022-10-26 13:37:51,499] {dbapi.py:216} INFO - Rows affected: 1
[2022-10-26 13:37:51,544] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=generos_raw_populate, execution_date=20220901T000000, start_date=20221026T133750, end_date=20221026T133751
[2022-10-26 13:37:51,629] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 13:37:51,865] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:27:32,645] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:32,672] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:27:32,672] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:32,672] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:27:32,672] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:27:32,703] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_populate> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:27:32,710] {standard_task_runner.py:52} INFO - Started process 261 to run task
[2022-10-26 14:27:32,716] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_populate', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp2hxma323', '--error-file', '/tmp/tmp_mfh09e2']
[2022-10-26 14:27:32,718] {standard_task_runner.py:80} INFO - Job 10: Subtask generos_raw_populate
[2022-10-26 14:27:32,911] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [running]> on host d860ef10ab5f
[2022-10-26 14:27:33,122] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_populate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:27:33,139] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:27:33,144] {dbapi.py:208} INFO - Running statement: 
                            INSERT INTO generos_raw (genero_id, genero) VALUES(1,'M');
                            INSERT INTO generos_raw (genero_id, genero) VALUES(2,'F');
                        , parameters: None
[2022-10-26 14:27:33,147] {dbapi.py:216} INFO - Rows affected: 1
[2022-10-26 14:27:33,187] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=generos_raw_populate, execution_date=20220901T000000, start_date=20221026T142732, end_date=20221026T142733
[2022-10-26 14:27:33,234] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:27:33,327] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-26 14:47:46,874] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:46,897] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-10-26 14:47:46,897] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:46,897] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-26 14:47:46,897] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-26 14:47:46,933] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): generos_raw_populate> on 2022-09-01 00:00:00+00:00
[2022-10-26 14:47:46,946] {standard_task_runner.py:52} INFO - Started process 288 to run task
[2022-10-26 14:47:46,950] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'load_raw_data', 'generos_raw_populate', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/raw-dag.py', '--cfg-path', '/tmp/tmp9w1ps1e9', '--error-file', '/tmp/tmpxfq0bxga']
[2022-10-26 14:47:46,952] {standard_task_runner.py:80} INFO - Job 10: Subtask generos_raw_populate
[2022-10-26 14:47:47,076] {task_command.py:369} INFO - Running <TaskInstance: load_raw_data.generos_raw_populate scheduled__2022-09-01T00:00:00+00:00 [running]> on host 4af2e895db31
[2022-10-26 14:47:47,231] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_raw_data
AIRFLOW_CTX_TASK_ID=generos_raw_populate
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-10-26 14:47:47,252] {base.py:68} INFO - Using connection ID 'postgres-default' for task execution.
[2022-10-26 14:47:47,257] {dbapi.py:208} INFO - Running statement: 
                            INSERT INTO generos_raw (genero_id, genero) VALUES(1,'M');
                            INSERT INTO generos_raw (genero_id, genero) VALUES(2,'F');
                        , parameters: None
[2022-10-26 14:47:47,261] {dbapi.py:216} INFO - Rows affected: 1
[2022-10-26 14:47:47,291] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_raw_data, task_id=generos_raw_populate, execution_date=20220901T000000, start_date=20221026T144746, end_date=20221026T144747
[2022-10-26 14:47:47,344] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-26 14:47:47,439] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
